# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: jayaditya
service: cloud-storeage-app

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  environment:
    CLERK_SECRET_KEY: ${env:CLERK_SECRET_KEY}
    CLERK_PUBLISHABLE_KEY: ${env:CLERK_PUBLISHABLE_KEY}
    CLERK_WEBHOOK_SECRET: ${env:CLERK_WEBHOOK_SECRET}

functions:
  app:
    handler: src/handler.handler
    events:
      - httpApi: '*'

package:
  individually: true

# optional: helps customize build
build:
  esbuild: true
  exclude: ['aws-sdk'] # optional

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node20
    platform: node
    entryPoints: ['src/handler.ts']
    outdir: 'dist'
